---

 - name: "Apacher httpd 서비스 기동하기" 
   hosts: webservers
   vars:
      pkg_web: httpd
      pkg_web_module: mod_ssl
      pkg_fw: firewalld
      dir_base: /var/www/html/index.html
      file_web_src: index.html 
      svc_web: httpd
      svc_fw: firewalld
      fw_http: http
      fw_https: https

   tasks:
   # 1) 패키지 설치 - httpd , mod_ssl , firewalld
   # 2) 웹서버 설정 - /var/www/html/index.html
   # 3) 서비스 기동 - httpd.service, firewalld.service
   # 4) 방화벽 등록 - http(80/tcp), https(443/tcp)

     - name: "1) 패키지 설치 - {{pkg_web}} , {{pkg_web_module}} , {{pkg_fw}}"
       yum: 
        name: 
         - "{{ pkg_web }}"
         - "{{pkg_web_module}}"
         - "{{ pkg_fw }}"
        state: present

     - name: "2) 웹서버 설정 - /var/www/html/index.html"
       ansible.builtin.copy:
        content: 'My First Web Page'
        dest:  "{{ dir_base }}  /  {{ file_web_src }}"
        


     - name: "3) 서비스 기동 - httpd.service, firewalld.service"
       ansible.builtin.service:
         name: "{{ servicenames }}"
         state: started
         enabled: yes
       loop: 
        - "{{ svc_web }}"
        - "{{ svc_fw }}"

     - name: "4) 방화벽 등록 - http(80/tcp), https(443/tcp)"
       ansible.builtin.firewalld:
          service: "{{ item }}"
          state: enabled
          permanent: yes
          immediate: yes
       loop:
         - "{{fw_http}}" 
         - "{{fw_https}}" 