---
- name: install and start apache httpd 
  hosts: webservers
  tasks:
   # yum install httpd
   - name : Install a package - httpd
     yum:
      name: httpd
      state: latest

   #scp files/index.html ansibles#:/var/www/html/index.html
   - name: copy from files/index.html to /var/www/html/index.html
     copy:
      src: files/index.html
      dest: /var/www/html/index.html
   #systemctl enable --now httpd\
   #systemctl restart httpd
   - name: start the web services - httpd
     service:
      name: httpd
      state: restarted
      enabled: yes


   #systemctl enable --now firewalld

   #firewall-cmd --permanent --add-services=http(80/tcp): firewall-cmd --reload
    - name: start the firewall - firewalld.service
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open the service with firewalld - http(80/tcp)
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes