---
- name: Restore the web1
  hosts: web1.example.com
  tasks:
   # firewalld-cmd --permanent --remove-service={http,https} 
   # firewall-cmd --reload
    - name: Remove the port to firewall - http(80/tcp)
      firewalld:
        service: http
        state: disabled
        permanent: yes
        immediate: yes
        


   #systemctl disable --now httpd
    - name: Down the service - httpd.service
      service:
        name: httpd
        state: stopped
        enabled: no

   #yum remove httpd -y 
    - name: remove packages - httpd 
      yum:
        name: httpd
        state: absent
        
   #rm -f /var/www/html/index.html
    - name: remove the file - /var/www/html/index.html
      file:
       path: /var/www/html/index.html
       state: absent