---
-   name: "MariaDB 서비스 동작"
    hosts: database_dev
    gather_facts: no
    vars: 
      mariadb_packages:
        - mariadb-server
        - python3-PyMySQL

    
    tasks:
        - name: "MariaDB 패키지 설치"
          yum:
            name: "{{item}}"
            state: present
          loop: "{{mariadb_packages}}"
          
        
           # -maridb-server 이 2개 쓴거랑 같음
                                        #- python3-PyMySQL 
        - name: "MariaDB 서비스 기동"
          service:
            name: mariadb
            state: started
            enabled: true

         